### ISSUE TITLE
Question about credentials

### ISSUE THREAD

**Issue by ararog** [shibayan/SendGridSharp#1]
I see on example API_USER and API_KEY, is API_USER the name of API_KEY?

**Comment by shibayan** [comment]
I added SendGrid API Key support. https://github.com/shibayan/SendGridSharp/commit/d9d971431a0b4d8f88b9bd7fcedb29afa08f6443
Please try ver 1.1.0. https://www.nuget.org/packages/SendGridSharp/1.1.0

Thanks.

**Comment by ararog** [comment]
Worked beautifully! Thanks!
